# Generated by Django 5.1.7 on 2025-04-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='github_link',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub Repository'),
        ),
    ]
