# Generated by Django 5.1.15 on 2026-04-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Mensagem")),
                ("read", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="projects/", verbose_name="Imagem"
                    ),
                ),
                (
                    "technologies",
                    models.CharField(
                        help_text="Separadas por vírgula",
                        max_length=300,
                        verbose_name="Tecnologias",
                    ),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub")),
                ("demo_url", models.URLField(blank=True, verbose_name="Demo")),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Destaque"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["-featured", "-created_at"],
            },
        ),
    ]
