# Generated by Django 5.1.15 on 2026-04-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
