# Generated by Django 5.1.15 on 2026-06-11 17:38

import django.db.models.deletion
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome (EN)"
                    ),
                ),
                (
                    "institution",
                    models.CharField(max_length=150, verbose_name="Instituição"),
                ),
                (
                    "hours",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Carga horária (h)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
            ],
            options={
                "verbose_name": "Certificação",
                "verbose_name_plural": "Certificações",
                "ordering": ["order", "id"],
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=150, verbose_name="Cargo")),
                (
                    "role_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Cargo (EN)"
                    ),
                ),
                ("company", models.CharField(max_length=150, verbose_name="Empresa")),
                (
                    "company_url",
                    models.URLField(blank=True, verbose_name="Site da empresa"),
                ),
                ("period", models.CharField(max_length=150, verbose_name="Período")),
                (
                    "period_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Período (EN)"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        help_text="Uma por linha", verbose_name="Atividades"
                    ),
                ),
                (
                    "details_en",
                    models.TextField(blank=True, verbose_name="Atividades (EN)"),
                ),
                (
                    "skills",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Habilidades"
                    ),
                ),
                (
                    "skills_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Habilidades (EN)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
            ],
            options={
                "verbose_name": "Experiência",
                "verbose_name_plural": "Experiências",
                "ordering": ["order", "id"],
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Título (EN)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Descrição (EN)"),
                ),
                (
                    "tags",
                    models.CharField(
                        help_text="Separadas por vírgula",
                        max_length=255,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "tags_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tags (EN)"
                    ),
                ),
                ("github_url", models.URLField(verbose_name="URL do GitHub")),
                (
                    "live_url",
                    models.URLField(blank=True, verbose_name="URL do site no ar"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["order", "id"],
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nome (EN)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Classe Font Awesome, ex: fas fa-server",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
            ],
            options={
                "verbose_name": "Categoria de competência",
                "verbose_name_plural": "Categorias de competências",
                "ordering": ["order", "id"],
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nome (EN)"
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Detalhe"
                    ),
                ),
                (
                    "detail_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Detalhe (EN)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Classe Font Awesome, ex: fab fa-python",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.skillcategory",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competência",
                "verbose_name_plural": "Competências",
                "ordering": ["order", "id"],
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
    ]
