# Generated by Django 5.2.16 on 2026-07-10 21:19
# Todos os projetos existentes são técnicos (default do campo); as demais
# categorias serão preenchidas via admin conforme surgirem projetos.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_typescript_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('tecnico', 'Projetos Técnicos'), ('empresarial', 'Soluções Empresariais'), ('sites', 'Sites & Landing Pages')], default='tecnico', max_length=20, verbose_name='Categoria'),
        ),
    ]
