# Generated by Django 5.2.16 on 2026-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_close_ibeize_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Caminho dentro de static/, ex.: images/projects/apex-reports.webp. Vazio: o card usa a capa neutra (projeto sem interface).",
                max_length=200,
                verbose_name="Preview",
            ),
        ),
    ]
