# Generated by Django 5.2.16 on 2026-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_set_project_previews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Caminho dentro de static/, ex.: images/projects/apex-reports.webp. Ideal 2:1 (920x460); outras proporções são cortadas pelo card. Vazio: o card usa a capa neutra (projeto sem interface).",
                max_length=200,
                verbose_name="Preview",
            ),
        ),
    ]
